let userCount = 100;
userCount = userCount + 5;
console.log("Users count:" + userCount);
userCount = userCount - 3;
console.log("Users count:" + userCount);
userCount *= 2;
console.log("Users count:" + userCount);
manCount = userCount / 2;
womanCount = userCount / 2;
console.log(userCount, manCount, womanCount);
